// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using meliPOS.models;

namespace meliPOS.Migrations
{
    [DbContext(typeof(MeliPOSDbContext))]
    partial class MeliPOSDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("meliPOS.models.usuarioLogin", b =>
                {
                    b.Property<string>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("nombre");

                    b.Property<string>("password");

                    b.Property<string>("token");

                    b.HasKey("id");

                    b.ToTable("UsuariosLogin");
                });
#pragma warning restore 612, 618
        }
    }
}
